openapi: 3.0.0
info:
  title: Appointment API
  version: 1.0.0
  description: |
    API de ejemplo para gestión de citas.
    Incluye todos los tipos de TypeScript disponibles.

servers:
  - url: http://localhost:3000/api/appointment
    description: Servidor local
  - url: https://api.example.com/appointment
    description: Servidor de producción

paths:
  /user-preferences:
    get:
      tags:
        - user-preferences
      summary: Obtener preferencias de usuario (Ejemplo con todos los tipos)
      operationId: getUserPreferences
      responses:
        '200':
          description: Preferencias del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  # STRING
                  userId:
                    type: string
                    description: ID del usuario
                  
                  username:
                    type: string
                    description: Nombre de usuario
                  
                  email:
                    type: string
                    format: email
                    description: Correo electrónico
                  
                  # NUMBER
                  age:
                    type: number
                    description: Edad del usuario
                  
                  score:
                    type: number
                    format: float
                    description: Puntuación (decimal)
                  
                  # INTEGER
                  loginCount:
                    type: integer
                    description: Número de inicios de sesión
                  
                  # BOOLEAN
                  isActive:
                    type: boolean
                    description: Usuario activo
                  
                  emailVerified:
                    type: boolean
                    description: Email verificado
                  
                  # DATE/DATETIME
                  createdAt:
                    type: string
                    format: date-time
                    description: Fecha de creación
                  
                  lastLogin:
                    type: string
                    format: date-time
                    description: Último inicio de sesión
                  
                  birthDate:
                    type: string
                    format: date
                    description: Fecha de nacimiento
                  
                  # ARRAY DE STRINGS
                  favoriteColors:
                    type: array
                    items:
                      type: string
                    description: Lista de colores favoritos
                  
                  # ARRAY DE NÚMEROS
                  ratings:
                    type: array
                    items:
                      type: number
                    description: Lista de calificaciones
                  
                  # ARRAY DE OBJETOS
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        message:
                          type: string
                        read:
                          type: boolean
                        timestamp:
                          type: string
                          format: date-time
                    description: Lista de notificaciones
                  
                  # OBJETO ANIDADO
                  address:
                    type: object
                    properties:
                      street:
                        type: string
                      city:
                        type: string
                      country:
                        type: string
                      zipCode:
                        type: string
                      coordinates:
                        type: object
                        properties:
                          lat:
                            type: number
                          lng:
                            type: number
                    description: Dirección del usuario
                  
                  # OBJETO CON PROPIEDADES OPCIONALES
                  settings:
                    type: object
                    properties:
                      fontSize:
                        type: number
                      soundEnabled:
                        type: boolean
                      autoSave:
                        type: boolean
                      timeout:
                        type: integer
                    description: Configuraciones adicionales
                  
                  # ANY (sin tipo específico)
                  metadata:
                    type: object
                    description: Metadatos adicionales (any)
                  
                  # NULL (nullable)
                  deletedAt:
                    type: string
                    format: date-time
                    nullable: true
                    description: Fecha de eliminación (puede ser null)

  /products:
    get:
      tags:
        - products
      summary: Obtener lista de productos (Ejemplo de Array)
      operationId: getProducts
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID del producto
                    
                    name:
                      type: string
                      description: Nombre del producto
                    
                    price:
                      type: number
                      format: float
                      description: Precio
                    
                    stock:
                      type: integer
                      description: Cantidad en stock
                    
                    available:
                      type: boolean
                      description: Disponible para compra
                    
                    category:
                      type: string
                      description: Categoría del producto
                    
                    tags:
                      type: array
                      items:
                        type: string
                      description: Etiquetas del producto
                    
                    images:
                      type: array
                      items:
                        type: string
                        format: uri
                      description: URLs de imágenes
                    
                    createdAt:
                      type: string
                      format: date-time
                      description: Fecha de creación

  /appointments:
    get:
      tags:
        - appointments
      summary: Obtener lista de citas (Ejemplo completo de array de objetos)
      operationId: getAppointments
      responses:
        '200':
          description: Lista de citas con objetos anidados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    appointmentId:
                      type: string
                      description: ID único de la cita
                    
                    patientId:
                      type: string
                      description: ID del paciente
                    
                    patientName:
                      type: string
                      description: Nombre del paciente
                    
                    doctorId:
                      type: string
                      description: ID del doctor
                    
                    doctorName:
                      type: string
                      description: Nombre del doctor
                    
                    specialty:
                      type: string
                      description: Especialidad médica
                    
                    appointmentDate:
                      type: string
                      format: date-time
                      description: Fecha y hora de la cita
                    
                    duration:
                      type: integer
                      description: Duración en minutos
                    
                    status:
                      type: string
                      description: Estado de la cita (pending, confirmed, completed, cancelled)
                    
                    isVirtual:
                      type: boolean
                      description: Indica si es cita virtual
                    
                    cost:
                      type: number
                      format: float
                      description: Costo de la cita
                    
                    location:
                      type: object
                      properties:
                        locationId:
                          type: string
                        name:
                          type: string
                        address:
                          type: string
                        city:
                          type: string
                        coordinates:
                          type: object
                          properties:
                            latitude:
                              type: number
                            longitude:
                              type: number
                      description: Ubicación de la cita
                    
                    patient:
                      type: object
                      properties:
                        id:
                          type: string
                        fullName:
                          type: string
                        email:
                          type: string
                        phone:
                          type: string
                        age:
                          type: integer
                      description: Información del paciente
                    
                    notes:
                      type: array
                      items:
                        type: object
                        properties:
                          noteId:
                            type: string
                          content:
                            type: string
                          createdBy:
                            type: string
                          createdAt:
                            type: string
                            format: date-time
                      description: Notas de la cita
                    
                    prescriptions:
                      type: array
                      items:
                        type: string
                      description: IDs de prescripciones
                    
                    attachments:
                      type: array
                      items:
                        type: object
                        properties:
                          fileId:
                            type: string
                          fileName:
                            type: string
                          fileUrl:
                            type: string
                          fileType:
                            type: string
                      description: Archivos adjuntos
                    
                    reminder:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        hours:
                          type: integer
                        sent:
                          type: boolean
                      description: Configuración de recordatorio
                    
                    createdAt:
                      type: string
                      format: date-time
                      description: Fecha de creación
                    
                    updatedAt:
                      type: string
                      format: date-time
                      description: Fecha de última actualización
                    
                    cancelledAt:
                      type: string
                      format: date-time
                      nullable: true
                      description: Fecha de cancelación

  /dashboard:
    get:
      tags:
        - dashboard
      summary: Dashboard del usuario (Objeto con array de objetos)
      operationId: getDashboard
      responses:
        '200':
          description: Dashboard completo del usuario con métricas y actividades
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: ID del usuario
                  
                  displayName:
                    type: string
                    description: Nombre para mostrar
                  
                  totalAppointments:
                    type: integer
                    description: Total de citas
                  
                  completedAppointments:
                    type: integer
                    description: Citas completadas
                  
                  pendingAppointments:
                    type: integer
                    description: Citas pendientes
                  
                  lastLoginAt:
                    type: string
                    format: date-time
                    description: Último inicio de sesión
                  
                  isPremium:
                    type: boolean
                    description: Usuario premium
                  
                  statistics:
                    type: object
                    properties:
                      totalSpent:
                        type: number
                        format: float
                      averageRating:
                        type: number
                        format: float
                      totalReviews:
                        type: integer
                    description: Estadísticas del usuario
                  
                  recentActivities:
                    type: array
                    items:
                      type: object
                      properties:
                        activityId:
                          type: string
                          description: ID de la actividad
                        type:
                          type: string
                          description: Tipo de actividad (appointment, payment, review)
                        description:
                          type: string
                          description: Descripción de la actividad
                        timestamp:
                          type: string
                          format: date-time
                          description: Fecha de la actividad
                        metadata:
                          type: object
                          properties:
                            appointmentId:
                              type: string
                            amount:
                              type: number
                            status:
                              type: string
                          description: Metadatos adicionales
                    description: Actividades recientes del usuario (array de objetos)
                  
                  upcomingAppointments:
                    type: array
                    items:
                      type: object
                      properties:
                        appointmentId:
                          type: string
                        doctorName:
                          type: string
                        specialty:
                          type: string
                        date:
                          type: string
                          format: date-time
                        location:
                          type: string
                        isVirtual:
                          type: boolean
                    description: Próximas citas (array de objetos)
                  
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        notificationId:
                          type: string
                        title:
                          type: string
                        message:
                          type: string
                        read:
                          type: boolean
                        priority:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                    description: Notificaciones del usuario (array de objetos)
                  
                  preferences:
                    type: object
                    properties:
                      theme:
                        type: string
                      language:
                        type: string
                      emailNotifications:
                        type: boolean
                      smsNotifications:
                        type: boolean
                    description: Preferencias del usuario

